"""relaciona usuario produtos

Revision ID: 6fe77fc77484
Revises: b153f19f3474
Create Date: 2026-04-23 16:43:48.338289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe77fc77484'
down_revision: Union[str, Sequence[str], None] = 'b153f19f3474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('criador_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'produtos', 'users', ['criador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_column('produtos', 'criador_id')
    # ### end Alembic commands ###
