"""ajuste forma de pagamento

Revision ID: 77181f7dcd15
Revises: ebcbf9a69a08
Create Date: 2026-06-17 21:55:12.696818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77181f7dcd15'
down_revision: Union[str, Sequence[str], None] = 'ebcbf9a69a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('valor_subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('vendas', sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('vendas', 'forma_pagamento',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendas', 'forma_pagamento',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('vendas', 'valor_desconto')
    op.drop_column('vendas', 'valor_subtotal')
    # ### end Alembic commands ###
