"""tabela de vendas

Revision ID: 9a7128f59d8b
Revises: fbb5b1a8c675
Create Date: 2026-06-15 23:03:59.905373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7128f59d8b'
down_revision: Union[str, Sequence[str], None] = 'fbb5b1a8c675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=False),
    sa.Column('status_pagamento', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('pvd_id', sa.Integer(), nullable=True),
    sa.Column('tipo_venda', sa.String(length=20), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('deleted_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['pvd_id'], ['ponto_de_venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_venda')
    op.drop_table('vendas')
    # ### end Alembic commands ###
