"""tabelas do fluxo de insumo e producao

Revision ID: a802848cb436
Revises: d51a72a8e40d
Create Date: 2026-05-14 20:59:18.153798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a802848cb436'
down_revision: Union[str, Sequence[str], None] = 'd51a72a8e40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('MATERIA_PRIMA', 'EMBALAGEM', name='tipo_insumo_enum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('unidade_de_medida', sa.Enum('KG', 'G', 'L', 'ML', 'UN', name='unidade_medida_enum'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('quantidade_estoque', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('entrada_insumo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_comprada', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('valor_total_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=20), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('fabricacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('custo_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'ESGOTADO', 'VENCIDO', 'CANCELADO', name='status_lote_enum'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_lote')
    )
    op.create_index(op.f('ix_lote_producao_produto_id'), 'lote_producao', ['produto_id'], unique=False)
    op.create_table('produto_insumo',
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_necessaria', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('produto_id', 'insumo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_insumo')
    op.drop_index(op.f('ix_lote_producao_produto_id'), table_name='lote_producao')
    op.drop_table('lote_producao')
    op.drop_table('entrada_insumo')
    op.drop_table('insumo')
    # ### end Alembic commands ###
