"""adiciona produtos ao banco de dados

Revision ID: b153f19f3474
Revises: 1dd71988e894
Create Date: 2026-04-22 19:27:36.146115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b153f19f3474'
down_revision: Union[str, Sequence[str], None] = '1dd71988e894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.Enum('GELEIA', 'MOLHO', 'conserva', name='tipo_produto_enum'), nullable=False),
    sa.Column('preco_varejo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_atacado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nivel_picancia', sa.Integer(), nullable=False),
    sa.Column('alergenicos', sa.String(length=255), nullable=False),
    sa.Column('tem_carolina_reaper', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('imagem_bucket', sa.String(length=50), nullable=True),
    sa.Column('imagem_path', sa.String(length=255), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('validade_meses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unidades_por_caixa', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('peso_gramas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_ativo'), 'produtos', ['ativo'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=True)
    op.create_index(op.f('ix_produtos_tipo'), 'produtos', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_tipo'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_ativo'), table_name='produtos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
