"""relaciona usuario produtos correçao

Revision ID: d1b7b8fd992e
Revises: 6fe77fc77484
Create Date: 2026-04-23 17:07:09.543805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b7b8fd992e'
down_revision: Union[str, Sequence[str], None] = '6fe77fc77484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
