"""create ponto de venda table

Revision ID: fbb5b1a8c675
Revises: a802848cb436
Create Date: 2026-06-11 02:10:20.724989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb5b1a8c675'
down_revision: Union[str, Sequence[str], None] = 'a802848cb436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('PESSOA_FISICA', 'RESTAURANTE', 'COMERCIO', name='tipo_cliente_enum'), nullable=False),
    sa.Column('identificador', sa.String(length=18), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco', sa.String(length=220), nullable=False),
    sa.Column('total_compras', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_compras', sa.Integer(), nullable=False),
    sa.Column('ultima_compra', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.Date(), nullable=False),
    sa.Column('atualizado_em', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identificador'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cliente_tipo'), 'cliente', ['tipo'], unique=False)
    op.create_table('ponto_de_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tipo_zona', sa.Enum('ZONA_SUL', 'ZONA_NORTE', 'ZONA_LESTE', 'ZONA_OESTE', name='tipo_zona_enum'), nullable=False),
    sa.Column('endereco', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('instagram', sa.String(length=50), nullable=True),
    sa.Column('google_maps_url', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('ultima_reposicao', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.Date(), nullable=False),
    sa.Column('atualizado_em', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ponto_de_venda_tipo_zona'), 'ponto_de_venda', ['tipo_zona'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ponto_de_venda_tipo_zona'), table_name='ponto_de_venda')
    op.drop_table('ponto_de_venda')
    op.drop_index(op.f('ix_cliente_tipo'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
